python: omnetpp.scave.utils: better error msg if scave_bindings cannot be loaded
Produces something like this:

ImportError: Could not import omnetpp.scave.scave_bindings -- OMNeT++ may not be fully built, or a required shared library is missing.
Files checked:
  /home/.../omnetpp/python/omnetpp/scave/scave_bindings.cpython-312-x86_64-linux-gnu.so -- found but failed to load: scave_bindings.cpython-312-x86_64-linux-gnu.so: invalid ELF header
  /home/.../omnetpp/python/omnetpp/scave/scave_bindings_dbg.cpython-312-x86_64-linux-gnu.so -- not found
  /home/.../omnetpp/python/omnetpp/scave/scave_bindings_sanitize.cpython-312-x86_64-linux-gnu.so -- not found

(cherry picked from commit da752bc1cf5cbd470645c6be69d7f53ac40925ee)